DROP TABLE IF EXISTS `cinema`;

ALTER TABLE `cinema`
  ADD PRIMARY KEY (`ID`);


DROP TABLE IF EXISTS `client`;
ALTER TABLE `client`
  ADD PRIMARY KEY (`ID`);


DROP TABLE IF EXISTS `film`;
ALTER TABLE `film`
  ADD PRIMARY KEY (`ID`);


DROP TABLE IF EXISTS `reservation`;
ALTER TABLE `reservation`
  ADD PRIMARY KEY (`ID`),
  ADD FOREIGN KEY (`ClientID`) REFERENCES `client` (`ID`),
  ADD FOREIGN KEY (`SeanceID`) REFERENCES `seance` (`ID`),
  ADD FOREIGN KEY (`TarifID`) REFERENCES `tarif` (`ID`);


DROP TABLE IF EXISTS `salle`;
ALTER TABLE `salle`
  ADD PRIMARY KEY (`ID`),
  ADD FOREIGN KEY (`CinemaID`) REFERENCES `cinema` (`ID`);


DROP TABLE IF EXISTS `seance`;
ALTER TABLE `seance`
  ADD PRIMARY KEY (`ID`),
  ADD FOREIGN KEY (`FilmID`) REFERENCES `film` (`ID`),
  ADD FOREIGN KEY (`SalleID`) REFERENCES `salle` (`ID`);


DROP TABLE IF EXISTS `tarif`;
ALTER TABLE `tarif`
  ADD PRIMARY KEY (`ID`);


DROP TABLE IF EXISTS `utilisateur`;
ALTER TABLE `utilisateur`
  ADD PRIMARY KEY (`ID`),
  ADD FOREIGN KEY (`CinemaID`) REFERENCES `cinema` (`ID`);

